package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Civilite generated by hbm2java
 */
@Entity
@Table(name = "civilite", catalog = "ticketshackds")
public class Civilite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCivilite;
	private String libelleCivilite;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Civilite() {
	}

	public Civilite(int idCivilite, String libelleCivilite) {
		this.idCivilite = idCivilite;
		this.libelleCivilite = libelleCivilite;
	}

	public Civilite(int idCivilite, String libelleCivilite,
			Set<Utilisateur> utilisateurs) {
		this.idCivilite = idCivilite;
		this.libelleCivilite = libelleCivilite;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@Column(name = "ID_CIVILITE", unique = true, nullable = false)
	public int getIdCivilite() {
		return this.idCivilite;
	}

	public void setIdCivilite(int idCivilite) {
		this.idCivilite = idCivilite;
	}

	@Column(name = "LIBELLE_CIVILITE", nullable = false, length = 30)
	public String getLibelleCivilite() {
		return this.libelleCivilite;
	}

	public void setLibelleCivilite(String libelleCivilite) {
		this.libelleCivilite = libelleCivilite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "civilite")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	
}
