package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "ticketshackds")
public class Commande implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCommande;
	private Utilisateur utilisateur;
	private String reference;
	private Date dateCreation;
	private Set<LigneCommande> ligneCommandes = new HashSet<LigneCommande>(0);

	public Commande() {
	}

	public Commande(int idCommande, Utilisateur utilisateur, String reference,
			Date dateCreation) {
		this.idCommande = idCommande;
		this.utilisateur = utilisateur;
		this.reference = reference;
		this.dateCreation = dateCreation;
	}

	public Commande(int idCommande, Utilisateur utilisateur, String reference,
			Date dateCreation, Set<LigneCommande> ligneCommandes) {
		this.idCommande = idCommande;
		this.utilisateur = utilisateur;
		this.reference = reference;
		this.dateCreation = dateCreation;
		this.ligneCommandes = ligneCommandes;
	}

	@Id
	@Column(name = "ID_COMMANDE", unique = true, nullable = false)
	public int getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(int idCommande) {
		this.idCommande = idCommande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTILISATEUR", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "REFERENCE", nullable = false, length = 50)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATION", nullable = false, length = 10)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commande")
	public Set<LigneCommande> getLigneCommandes() {
		return this.ligneCommandes;
	}

	public void setLigneCommandes(Set<LigneCommande> ligneCommandes) {
		this.ligneCommandes = ligneCommandes;
	}

}
