package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "ticketshackds")
public class Departement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idDep;
	private String libelleDep;
	private Set<Occurence> occurences = new HashSet<Occurence>(0);

	public Departement() {
	}

	public Departement(int idDep, String libelleDep) {
		this.idDep = idDep;
		this.libelleDep = libelleDep;
	}

	public Departement(int idDep, String libelleDep, Set<Occurence> occurences) {
		this.idDep = idDep;
		this.libelleDep = libelleDep;
		this.occurences = occurences;
	}

	@Id
	@Column(name = "ID_DEP", unique = true, nullable = false)
	public int getIdDep() {
		return this.idDep;
	}

	public void setIdDep(int idDep) {
		this.idDep = idDep;
	}

	@Column(name = "LIBELLE_DEP", nullable = false, length = 100)
	public String getLibelleDep() {
		return this.libelleDep;
	}

	public void setLibelleDep(String libelleDep) {
		this.libelleDep = libelleDep;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	public Set<Occurence> getOccurences() {
		return this.occurences;
	}

	public void setOccurences(Set<Occurence> occurences) {
		this.occurences = occurences;
	}

}
