package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LigneCommande generated by hbm2java
 */
@Entity
@Table(name = "ligne_commande", catalog = "ticketshackds")
public class LigneCommande implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idLigneCommande;
	private Commande commande;
	private Tarif tarif;
	private Occurence occurence;
	private int quantitie;

	public LigneCommande() {
	}

	public LigneCommande(int idLigneCommande, Commande commande, Tarif tarif,
			Occurence occurence, int quantitie) {
		this.idLigneCommande = idLigneCommande;
		this.commande = commande;
		this.tarif = tarif;
		this.occurence = occurence;
		this.quantitie = quantitie;
	}

	@Id
	@Column(name = "ID_LIGNE_COMMANDE", unique = true, nullable = false)
	public int getIdLigneCommande() {
		return this.idLigneCommande;
	}

	public void setIdLigneCommande(int idLigneCommande) {
		this.idLigneCommande = idLigneCommande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COMMANDE", nullable = false)
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TARIF", nullable = false)
	public Tarif getTarif() {
		return this.tarif;
	}

	public void setTarif(Tarif tarif) {
		this.tarif = tarif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_OCCURENCE", nullable = false)
	public Occurence getOccurence() {
		return this.occurence;
	}

	public void setOccurence(Occurence occurence) {
		this.occurence = occurence;
	}

	@Column(name = "QUANTITIE", nullable = false)
	public int getQuantitie() {
		return this.quantitie;
	}

	public void setQuantitie(int quantitie) {
		this.quantitie = quantitie;
	}

}
