package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Occurence generated by hbm2java
 */
@Entity
@Table(name = "occurence", catalog = "ticketshackds")
public class Occurence implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idOccurence;
	private Evenement evenement;
	private Departement departement;
	private Date date;
	private String lieu;
	private Integer nombrePlaces;
	private Date dateFin;
	private Set<Tarif> tarifs = new HashSet<Tarif>(0);
	private Set<LigneCommande> ligneCommandes = new HashSet<LigneCommande>(0);

	public Occurence() {
	}

	public Occurence(int idOccurence, Evenement evenement,
			Departement departement, String lieu) {
		this.idOccurence = idOccurence;
		this.evenement = evenement;
		this.departement = departement;
		this.lieu = lieu;
	}

	public Occurence(int idOccurence, Evenement evenement,
			Departement departement, Date date, String lieu,
			Integer nombrePlaces, Date dateFin, Set<Tarif> tarifs,
			Set<LigneCommande> ligneCommandes) {
		this.idOccurence = idOccurence;
		this.evenement = evenement;
		this.departement = departement;
		this.date = date;
		this.lieu = lieu;
		this.nombrePlaces = nombrePlaces;
		this.dateFin = dateFin;
		this.tarifs = tarifs;
		this.ligneCommandes = ligneCommandes;
	}

	@Id
	@Column(name = "ID_OCCURENCE", unique = true, nullable = false)
	public int getIdOccurence() {
		return this.idOccurence;
	}

	public void setIdOccurence(int idOccurence) {
		this.idOccurence = idOccurence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EVENEMENT", nullable = false)
	public Evenement getEvenement() {
		return this.evenement;
	}

	public void setEvenement(Evenement evenement) {
		this.evenement = evenement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEP", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "LIEU_", nullable = false, length = 200)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	@Column(name = "NOMBRE_PLACES")
	public Integer getNombrePlaces() {
		return this.nombrePlaces;
	}

	public void setNombrePlaces(Integer nombrePlaces) {
		this.nombrePlaces = nombrePlaces;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "occurence")
	public Set<Tarif> getTarifs() {
		return this.tarifs;
	}

	public void setTarifs(Set<Tarif> tarifs) {
		this.tarifs = tarifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "occurence")
	public Set<LigneCommande> getLigneCommandes() {
		return this.ligneCommandes;
	}

	public void setLigneCommandes(Set<LigneCommande> ligneCommandes) {
		this.ligneCommandes = ligneCommandes;
	}

}
