package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatutUtilisateur generated by hbm2java
 */
@Entity
@Table(name = "statut_utilisateur", catalog = "ticketshackds")
public class StatutUtilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idStatutUtilisateur;
	private String libelleStatutUtilisateur;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public StatutUtilisateur() {
	}

	public StatutUtilisateur(int idStatutUtilisateur,
			String libelleStatutUtilisateur) {
		this.idStatutUtilisateur = idStatutUtilisateur;
		this.libelleStatutUtilisateur = libelleStatutUtilisateur;
	}

	public StatutUtilisateur(int idStatutUtilisateur,
			String libelleStatutUtilisateur, Set<Utilisateur> utilisateurs) {
		this.idStatutUtilisateur = idStatutUtilisateur;
		this.libelleStatutUtilisateur = libelleStatutUtilisateur;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@Column(name = "ID_STATUT_UTILISATEUR", unique = true, nullable = false)
	public int getIdStatutUtilisateur() {
		return this.idStatutUtilisateur;
	}

	public void setIdStatutUtilisateur(int idStatutUtilisateur) {
		this.idStatutUtilisateur = idStatutUtilisateur;
	}

	@Column(name = "LIBELLE_STATUT_UTILISATEUR", nullable = false, length = 50)
	public String getLibelleStatutUtilisateur() {
		return this.libelleStatutUtilisateur;
	}

	public void setLibelleStatutUtilisateur(String libelleStatutUtilisateur) {
		this.libelleStatutUtilisateur = libelleStatutUtilisateur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statutUtilisateur")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
