package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tarif generated by hbm2java
 */
@Entity
@Table(name = "tarif", catalog = "ticketshackds")
public class Tarif implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTarif;
	private Occurence occurence;
	private String libelleTarif;
	private long prix;
	private Set<LigneCommande> ligneCommandes = new HashSet<LigneCommande>(0);

	public Tarif() {
	}

	public Tarif(int idTarif, Occurence occurence, String libelleTarif,
			long prix) {
		this.idTarif = idTarif;
		this.occurence = occurence;
		this.libelleTarif = libelleTarif;
		this.prix = prix;
	}

	public Tarif(int idTarif, Occurence occurence, String libelleTarif,
			long prix, Set<LigneCommande> ligneCommandes) {
		this.idTarif = idTarif;
		this.occurence = occurence;
		this.libelleTarif = libelleTarif;
		this.prix = prix;
		this.ligneCommandes = ligneCommandes;
	}

	@Id
	@Column(name = "ID_TARIF", unique = true, nullable = false)
	public int getIdTarif() {
		return this.idTarif;
	}

	public void setIdTarif(int idTarif) {
		this.idTarif = idTarif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_OCCURENCE", nullable = false)
	public Occurence getOccurence() {
		return this.occurence;
	}

	public void setOccurence(Occurence occurence) {
		this.occurence = occurence;
	}

	@Column(name = "LIBELLE_TARIF", nullable = false, length = 50)
	public String getLibelleTarif() {
		return this.libelleTarif;
	}

	public void setLibelleTarif(String libelleTarif) {
		this.libelleTarif = libelleTarif;
	}

	@Column(name = "PRIX", nullable = false, precision = 10, scale = 0)
	public long getPrix() {
		return this.prix;
	}

	public void setPrix(long prix) {
		this.prix = prix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarif")
	public Set<LigneCommande> getLigneCommandes() {
		return this.ligneCommandes;
	}

	public void setLigneCommandes(Set<LigneCommande> ligneCommandes) {
		this.ligneCommandes = ligneCommandes;
	}

}
