package fr.afcepf.al27.ticketshack.entity.entity;

// Generated 3 juin 2016 13:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "ticketshackds")
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUtilisateur;
	private StatutUtilisateur statutUtilisateur;
	private Reduction reduction;
	private Civilite civilite;
	private String nom;
	private String prenom;
	private String mail;
	private String mdp;
	private String mobile;
	private Date naissance;
	private Date inscription;
	private Set<Theme> themes = new HashSet<Theme>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur, StatutUtilisateur statutUtilisateur,
			String nom, String prenom, String mail, String mdp, Date inscription) {
		this.idUtilisateur = idUtilisateur;
		this.statutUtilisateur = statutUtilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.mail = mail;
		this.mdp = mdp;
		this.inscription = inscription;
	}

	public Utilisateur(int idUtilisateur, StatutUtilisateur statutUtilisateur,
			Reduction reduction, Civilite civilite, String nom, String prenom,
			String mail, String mdp, String mobile, Date naissance,
			Date inscription, Set<Theme> themes, Set<Commande> commandes) {
		this.idUtilisateur = idUtilisateur;
		this.statutUtilisateur = statutUtilisateur;
		this.reduction = reduction;
		this.civilite = civilite;
		this.nom = nom;
		this.prenom = prenom;
		this.mail = mail;
		this.mdp = mdp;
		this.mobile = mobile;
		this.naissance = naissance;
		this.inscription = inscription;
		this.themes = themes;
		this.commandes = commandes;
	}

	@Id
	@Column(name = "ID_UTILISATEUR", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_STATUT_UTILISATEUR", nullable = false)
	public StatutUtilisateur getStatutUtilisateur() {
		return this.statutUtilisateur;
	}

	public void setStatutUtilisateur(StatutUtilisateur statutUtilisateur) {
		this.statutUtilisateur = statutUtilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REDUCTION")
	public Reduction getReduction() {
		return this.reduction;
	}

	public void setReduction(Reduction reduction) {
		this.reduction = reduction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CIVILITE")
	public Civilite getCivilite() {
		return this.civilite;
	}

	public void setCivilite(Civilite civilite) {
		this.civilite = civilite;
	}

	@Column(name = "NOM", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM_", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "MAIL_", nullable = false, length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "MDP_", nullable = false, length = 50)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column(name = "MOBILE_", length = 50)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NAISSANCE_", length = 10)
	public Date getNaissance() {
		return this.naissance;
	}

	public void setNaissance(Date naissance) {
		this.naissance = naissance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INSCRIPTION", nullable = false, length = 10)
	public Date getInscription() {
		return this.inscription;
	}

	public void setInscription(Date inscription) {
		this.inscription = inscription;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "utilisateurs")
	public Set<Theme> getThemes() {
		return this.themes;
	}

	public void setThemes(Set<Theme> themes) {
		this.themes = themes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
